Update CICD.yml

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -167,17 +167,49 @@ jobs:
 #          max-attempts: 3
 #          retry-delay: 10s
 
-      - name: Check deploy server URL with dynamic target
-        uses: jtalk/url-health-check-action@v3
-        with:
-          # 현재 EC2 아이피 + hc[건강체크] + 방금 연 서버이름 [green or blue] + env 를 체크
-          # 포트는 nginx 에서 라우팅할거임
-          url: http://${{ secrets.SPRING_BOOT_DOCKER_IP }}/hc/${{ env.TARGET_UPSTREAM }}/env
-          # 최대 3번
-          max-attempts: 3
-          # 10초 간격으로
-          retry-delay: 10s
+#      - name: Check deploy server URL with dynamic target
+#        uses: jtalk/url-health-check-action@v3
+#        with:
+#          # 현재 EC2 아이피 + hc[건강체크] + 방금 연 서버이름 [green or blue] + env 를 체크
+#          # 포트는 nginx 에서 라우팅할거임
+#          url: http://${{ secrets.SPRING_BOOT_DOCKER_IP }}/hc/${{ env.TARGET_UPSTREAM }}/env
+#          # 최대 3번
+#          max-attempts: 3
+#          # 10초 간격으로
+#          retry-delay: 10s
 
+      - name: Check deploy server URL with retries
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.SPRING_BOOT_DOCKER_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            URL="http://${{ secrets.SPRING_BOOT_DOCKER_IP }}/hc/${{ env.TARGET_UPSTREAM }}/env"
+            MAX_ATTEMPTS=3
+            RETRY_DELAY=10
+            ATTEMPT=1
+            STATUS=0
+            
+            while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
+            STATUS=$(curl -o /dev/null -w "%{http_code}" "$URL")
+            echo "Attempt $ATTEMPT: HTTP Status Code: $STATUS"
+            
+            if [ "$STATUS" -eq 200 ]; then
+            echo "Server is up!"
+            exit 0
+            fi
+            
+            if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
+            echo "Server is down! Retrying in $RETRY_DELAY seconds..."
+            sleep $RETRY_DELAY
+            fi
+            
+            ATTEMPT=$((ATTEMPT+1))
+            done
+            
+            echo "Server is still down after $MAX_ATTEMPTS attempts!"
+            exit 1
       # nginx 에있는 파일내에 있는 url 변경하기
       ## 파일 경로 = [etc/nginx/conf.d/service-env.inc]
       - name: Change nginx upstream
